# Generated by Django 4.1.5 on 2023-01-22 13:51

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPassUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=255, verbose_name='first name')),
                ('name_sur', models.CharField(max_length=255, verbose_name='surname')),
                ('name_pat', models.CharField(blank=True, max_length=255, null=True, verbose_name='patronymic')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='e-mail')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'pereval_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AddedMPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=30, verbose_name='object type')),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(max_length=255, verbose_name='other titles')),
                ('connects', models.CharField(max_length=255, verbose_name='pass connects')),
                ('level_win', models.CharField(blank=True, max_length=2, null=True, verbose_name='winter difficulty level')),
                ('level_spr', models.CharField(blank=True, max_length=2, null=True, verbose_name='spring difficulty level')),
                ('level_sum', models.CharField(blank=True, max_length=2, null=True, verbose_name='summer difficulty level')),
                ('level_aut', models.CharField(blank=True, max_length=2, null=True, verbose_name='autumn difficulty level')),
                ('add_time', models.DateTimeField(verbose_name='added on')),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='new', max_length=10)),
            ],
            options={
                'verbose_name': 'added mountain pass',
                'verbose_name_plural': 'added mountain passes',
                'db_table': 'pereval_added',
            },
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lon', models.FloatField(verbose_name='longitude')),
                ('height', models.IntegerField()),
            ],
            options={
                'verbose_name': 'mountain pass coordinates',
                'verbose_name_plural': "mountain passes' coordinates",
                'db_table': 'pereval_coords',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.BinaryField(null=True)),
                ('mpass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpass_images', to='mpass.addedmpass')),
            ],
            options={
                'verbose_name': 'mountain pass image',
                'verbose_name_plural': "mountain passes' images",
                'db_table': 'pereval_images',
            },
        ),
        migrations.AddField(
            model_name='addedmpass',
            name='coords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpass.coords'),
        ),
        migrations.AddField(
            model_name='addedmpass',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
